### ISSUE TITLE
using SmartGrid features creates parsing error

### ISSUE THREAD

**Issue by hlinden** [hansmi/wp2reg-luxws#51]
I've started using the SmartGrid feature on my Novelan LAD7 today. wp2reg-luxws 0.4.0 does fail to parse the state XML from the heatpump since then.

A verbose log is attached here:  [journal.txt](https://github.com/hansmi/wp2reg-luxws/files/11927210/journal.txt)

I suspect this value in this element to be the culprit: ![newelement2](https://github.com/hansmi/wp2reg-luxws/assets/4718458/904c4e43-f700-45dd-b7dc-d689be74892f)

values can range from 1 to 4 with the following meanings:

1 - EVU lockdown active, compressor won't start
2 - operation at lowered temperatures (to save electric energy)
3 - normal operation
4 - operation at raised temperatures (to store excessive electric energy as heat energy)

If you could add this key to the exporter, that would be nice. Thank you :)

**Comment by hansmi** [comment]
Thank you for the very useful verbose log and the detailed issue description. I merged your #52 and followed up with a commit to generalize the code a bit.

**Comment by hansmi** [comment]
I tagged [version 0.4.1](https://github.com/hansmi/wp2reg-luxws/releases/tag/v0.4.1) including the changes from #52.
