### ISSUE TITLE
Release 0.2.1

### ISSUE THREAD

**Issue by dagerber** [hansmi/wp2reg-luxws#7]
Could you make another release with the latest changes?

Sidenote:
I tried to build it myself, but could not run the executable built as shown below, probably line-feed problems in the code?
Error I got when running "docker run -it wp2reg:latest"

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

Dockerfile I used:

```
#################
## Build
#################
FROM golang:1.16-buster AS build

RUN git clone https://github.com/hansmi/wp2reg-luxws.git
WORKDIR wp2reg-luxws/luxws-exporter
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -o /bin/luxws-exporter

#################
## Runtime
#################

FROM alpine:latest
RUN apk add bash 
RUN apk --update add busybox-extras
RUN mkdir -p /run

COPY --from=build /bin/luxws-exporter /run/

EXPOSE 8111
CMD ["/run/luxws-exporter", "-verbose", "-controller.address", "192.168.1.18:8214", "-controller.language", "de", "-web.listen-address", ":8111"]
```

**Comment by hansmi** [comment]
@dagerber, I released [version 0.3.0 with the corresponding binary packages](https://github.com/hansmi/wp2reg-luxws/releases/tag/v0.3.0).

A local test with the following Dockerfile was successful:

```dockerfile
FROM golang:1.18-buster AS build

RUN git clone https://github.com/hansmi/wp2reg-luxws.git
WORKDIR wp2reg-luxws/luxws-exporter
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -o /tmp/luxws-exporter
```

Command used:

```shell
docker build --rm --tag lebuild . && docker run lebuild /tmp/luxws-exporter -help
```

**Comment by hansmi** [comment]
I also realized what the problem is with the ominous "no such file or directory". A plain `go build` produces an executable still linking against libc. Alpine uses musl, not glibc as Debian does. You either need to adjust the build flags for a fully static binary (there are many guides on the web) or use a runtime environment with the correct glibc version (e.g. Debian).

**Comment by dagerber** [comment]
Thank you very much!
I now have your exporter running in a Docker container on my Synology NAS, along with Prometheus and Grafana.

Something else: I get the following output (Alpha Innotec, LW150A):
```
# TYPE luxws_up gauge
luxws_up{status="collection via LuxWS protocol failed: item with name \"Wärmemenge\" not found"} 0
```
Can I ignore it or should I open another issue?

**Comment by hansmi** [comment]
@dagerber, please open another issue and include the relevant output produced with the `-verbose` flag.
